name: scala
services:
  spark-server:
    entrypoint:
    - /opt/spark/sbin/start-master.sh
    environment:
      SPARK_LOCAL_IP: spark-server
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKLOAD: master
    image: apache/spark:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 7077
      published: "7077"
      protocol: tcp
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
  spark-shell:
    command:
    - /opt/spark/bin/spark-shell
    image: apache/spark:latest
    networks:
      default: null
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      source: /home/mzd/Lab/scala/work
      target: /opt/spark/work-dir
      bind:
        create_host_path: true
  spark-worker:
    depends_on:
      spark-server:
        condition: service_started
        required: true
    entrypoint:
    - /opt/spark/sbin/start-worker.sh
    - spark://spark-server:7077
    environment:
      SPARK_NO_DAEMONIZE: "true"
    image: apache/spark:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /home/mzd/Lab/scala/work
      target: /opt/spark/work-dir
      bind:
        create_host_path: true
networks:
  default:
    name: scala_default
