
services:
  spark-server:
    image: apache/spark:latest
    entrypoint: 
      - /opt/spark/sbin/start-master.sh
    environment:
      - SPARK_LOCAL_IP=spark-server
      - SPARK_WORKLOAD=master
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"  # Spark Server port
      - "8080:8080"  # Spark Server Web UI port

