
services:
  spark-shell:
    image: apache/spark:latest
    tty: true
    stdin_open: true
    command: 
      - /opt/spark/bin/spark-shell
    environment:
     - SPARK_LOCAL_IP=spark-shell
    ports:
     - 4040:4040
    volumes: 
      - ./work:/opt/spark/work-dir
